### ISSUE TITLE
Compiling issues with DMD 2.067

### ISSUE THREAD

**Issue by aubade** [Jebbs/DSFML#168]
v2.067 is brand new, and as usual it breaks some code and triggers some new deprecations: I haven't yet dived in to fix stuff but here's what it complains about to me when I run dub build dsfml:

```
DSFML\src\dsfml\audio\soundstream.d(374): Warning: instead of C-style syntax, us
e D-style syntax 'uint[BufferCount] m_buffers'
DSFML\src\dsfml\audio\soundstream.d(380): Warning: instead of C-style syntax, us
e D-style syntax 'bool[BufferCount] m_endBuffers'
DSFML\src\dsfml\network\tcpsocket.d(197): Error: module dsfml.network.tcpsocket
struct dsfml.network.packet.sfPacket is private
DSFML\src\dsfml\network\tcpsocket.d(201): Error: module dsfml.network.tcpsocket
struct dsfml.network.packet.sfPacket is private
DSFML\src\dsfml\network\tcplistener.d(113): Error: module dsfml.network.tcpliste
ner struct dsfml.network.tcpsocket.sfTcpSocket is private
DSFML\src\dsfml\network\udpsocket.d(179): Error: module dsfml.network.udpsocket
struct dsfml.network.packet.sfPacket is private
DSFML\src\dsfml\network\udpsocket.d(183): Error: module dsfml.network.udpsocket
struct dsfml.network.packet.sfPacket is private
DSFML\src\dsfml\network\socketselector.d(127): Error: module dsfml.network.socke
tselector struct dsfml.network.tcplistener.sfTcpListener is private
DSFML\src\dsfml\network\socketselector.d(128): Error: module dsfml.network.socke
tselector struct dsfml.network.tcpsocket.sfTcpSocket is private
DSFML\src\dsfml\network\socketselector.d(129): Error: module dsfml.network.socke
tselector struct dsfml.network.udpsocket.sfUdpSocket is private
DSFML\src\dsfml\network\socketselector.d(133): Error: module dsfml.network.socke
tselector struct dsfml.network.tcplistener.sfTcpListener is private
DSFML\src\dsfml\network\socketselector.d(134): Error: module dsfml.network.socke
tselector struct dsfml.network.tcpsocket.sfTcpSocket is private
DSFML\src\dsfml\network\socketselector.d(135): Error: module dsfml.network.socke
tselector struct dsfml.network.udpsocket.sfUdpSocket is private
DSFML\src\dsfml\network\socketselector.d(147): Error: module dsfml.network.socke
tselector struct dsfml.network.tcplistener.sfTcpListener is private
DSFML\src\dsfml\network\socketselector.d(148): Error: module dsfml.network.socke
tselector struct dsfml.network.tcpsocket.sfTcpSocket is private
DSFML\src\dsfml\network\socketselector.d(149): Error: module dsfml.network.socke
tselector struct dsfml.network.udpsocket.sfUdpSocket is private
FAIL DSFML\.dub\build\library-debug-windows-x86-dmd_2067-304018D935C3B4C4A4F02B6
72E3B6186\ dsfml staticLibrary
```

**Comment by Jebbs** [comment]
I was worried about this. I haven't had time to try building it with the beta and I saw yesterday that it had been released. 

I'm on spring break now, so I can take care of this. I actually hope to have all the code for the next release done this weekend.

**Comment by aubade** [comment]
Oooooh, is that the 2.1 release? I've been really looking forward to it.

**Comment by Jebbs** [comment]
Yep, that's the one.

I'm also considering re-releasing 2.0 as well since a lot of things have improved since then and the only difference between the two internally will be the sfml sources.

**Comment by Jebbs** [comment]
I haven't done aything for this yet, but it is a little worrisome.

Do you know how backwards compatible this compiler is with old code? As in, things that compile with the new compiler will still compile with older compilers, right? I'm hoping that we don't need the most up to date compiler to allow usage with DSFML.

**Comment by aubade** [comment]
I believe so? All the changes it wanted me to make for 2.067 still work fine with 2.066.1, at least!

**Comment by Jebbs** [comment]
That's good enough for me!

**Comment by Jebbs** [comment]
What OS are you building on? I just upgraded to 2.067 on Linux, and built everything with no errors.

Maybe you just have some old code? The 2.1 branch is building static libraries and unit tests on all compilers.

https://travis-ci.org/Jebbs/DSFML/builds/57068940

**Comment by aubade** [comment]
...oh, sure enough. My attempts to make newer DUB work with my non-public project pulled in a v. obsolete local fork of DSFML. Sorry!

**Comment by Jebbs** [comment]
No worries. If you want to try out the new branch it should be available on dub already, you'll just have to build the new backend: https://github.com/Jebbs/DSFMLC (I decided to change the name)

**Comment by aubade** [comment]
Fantastic! I'll probably take a look at soon.

**Comment by Jebbs** [comment]
Code wise, everything is done that I will want to do for this release. It might need some cleaning up, but it should all be there. I was going to put together some packages together to make it easier for people to try things out, but it is pretty much tutorials and documentation from here on out.

**Comment by aubade** [comment]
Okay, the upgrade process is getting smoother :D My engine runs with the rc1 branch without a hiccup. And since you combined the DSFMLC and SFML sources, I can actually build DSFMLC on windows so I'm not totally reliant on your binaries.

Things are starting to rock just a little bit harder. :heart:

**Comment by Jebbs** [comment]
That looks great! Nice!

You should also have better performance now too. Text drawing was doing some stupid stuff before and took up a lot of CPU.

**Comment by aubade** [comment]
Awesome! It's been a bit since i've gotten a chance to run this on anything remotely low-spec (when i uncap it it tends to hit several thousand fps), but i look forward to the opportunity!
