### ISSUE TITLE
dsfml:audio 2.1.0 wont compile with dmd 2071.0

### ISSUE THREAD

**Issue by grogancolin** [Jebbs/DSFML#223]
```
⇒  dub build
Performing "debug" build using dmd for x86_64.
dsfml:system 2.1.0: target for configuration "library" is up to date.
dsfml:audio 2.1.0: building configuration "library"...
../../.dub/packages/dsfml-2.1.0/src/dsfml/audio/soundbuffer.d(63,21): Error: function object.Object.toString () is not callable using argument types (const(char)*)
../../.dub/packages/dsfml-2.1.0/src/dsfml/audio/soundbuffer.d(148,22): Error: function object.Object.toString () is not callable using argument types (const(char)*)
../../.dub/packages/dsfml-2.1.0/src/dsfml/audio/soundbuffer.d(172,22): Error: function object.Object.toString () is not callable using argument types (const(char)*)
../../.dub/packages/dsfml-2.1.0/src/dsfml/audio/soundbuffer.d(196,22): Error: function object.Object.toString () is not callable using argument types (const(char)*)
../../.dub/packages/dsfml-2.1.0/src/dsfml/audio/soundbuffer.d(222,22): Error: function object.Object.toString () is not callable using argument types (const(char)*)
../../.dub/packages/dsfml-2.1.0/src/dsfml/audio/soundbuffer.d(247,22): Error: function object.Object.toString () is not callable using argument types (const(char)*)
../../.dub/packages/dsfml-2.1.0/src/dsfml/audio/soundrecorder.d(61,21): Error: function object.Object.toString () is not callable using argument types (const(char)*)
../../.dub/packages/dsfml-2.1.0/src/dsfml/audio/soundrecorder.d(92,21): Error: function object.Object.toString () is not callable using argument types (const(char)*)
../../.dub/packages/dsfml-2.1.0/src/dsfml/audio/soundstream.d(82,21): Error: function object.Object.toString () is not callable using argument types (const(char)*)
../../.dub/packages/dsfml-2.1.0/src/dsfml/audio/soundstream.d(278,21): Error: function object.Object.toString () is not callable using argument types (const(char)*)
dmd failed with exit code 1.
```

**Comment by aubade** [comment]
Have you updated your DSFML recently? The fix for this was committed about a week ago.

**Comment by dmi7ry** [comment]
Using your instruction from site ([Building DSFML](https://jebbs.github.io/DSFML/docs/buildingfromsource.html)):

> git clone -b v2.1.0 --depth 1 https://github.com/Jebbs/DSFML.git
> cd DSFML
> rdmd build

result is:

    Building for Windows with dmd

    Building static libraries!
    Building system module.
    Building audio module.
    src\dsfml\audio\soundbuffer.d(63): Error: function object.Object.toString () is not callable using argument types (const(char)*)
    src\dsfml\audio\soundbuffer.d(148): Error: function object.Object.toString () is not callable using argument types (const(char)*)
    src\dsfml\audio\soundbuffer.d(172): Error: function object.Object.toString () is not callable using argument types (const(char)*)
    src\dsfml\audio\soundbuffer.d(196): Error: function object.Object.toString () is not callable using argument types (const(char)*)
    src\dsfml\audio\soundbuffer.d(222): Error: function object.Object.toString () is not callable using argument types (const(char)*)
    src\dsfml\audio\soundbuffer.d(247): Error: function object.Object.toString () is not callable using argument types (const(char)*)
    src\dsfml\audio\soundrecorder.d(61): Error: function object.Object.toString () is not callable using argument types (const(char)*)
    src\dsfml\audio\soundrecorder.d(92): Error: function object.Object.toString () is not callable using argument types (const(char)*)
    src\dsfml\audio\soundstream.d(82): Error: function object.Object.toString () is not callable using argument types (const(char)*)
    src\dsfml\audio\soundstream.d(278): Error: function object.Object.toString () is not callable using argument types (const(char)*)

**Comment by grogancolin** [comment]
I'm using the dub release 2.1.0, so no, I haven't updated it, and don't really plan to until dub gets updated.

I generally lag behind dmd by a release or two anyway, so no matter to me. Was simply reporting it here so it could get fixed. Good to know it already has!

👍

**Comment by Jebbs** [comment]
Yeah, dmd put dsfml in kind of a weird spot. I hadn't planned on doing any partial releases, but it looks like I may have to.

It's a little unconventional, but if you use master instead of 2.1.0 in your dub file it will work. I guess 2.1.1 is coming out soon.

**Comment by dmi7ry** [comment]
but if you use master instead of 2.1.0 in your dub file it will work

I tried just now, but result is same. So, will wait 2.1.1

**Comment by Jebbs** [comment]
Damn it, you're right. Master dub.json still pulls in dsfml 2.1.0 instead of using the new code. Will fix tonight.

**Comment by grogancolin** [comment]
I thought dub doesn't support (or maybe just doesnt promote) use of master in packages?
The way I understood it, we should always aim to do tagged releases for things on code.dlang.org.

**Comment by Jebbs** [comment]
It'll work, but it's currently deprecated. I only suggested it as a quick and dirty fix, but I'll have an actual fix tonight.

**Comment by grogancolin** [comment]
Ah, apologies. I misread!

**Comment by Jebbs** [comment]
Ok, just tagged the current master as v2.1.1. Once dub updates itself you shouldn't have any issues.

**Comment by dmi7ry** [comment]
Don't forget to change

    git clone -b v2.1.0 --depth 1 https://github.com/Jebbs/DSFML.git

to `2.1.1` [here](http://dsfml.com/docs/buildingfromsource.html)

**Comment by Jebbs** [comment]
Yes, thank you. I also need to update the packages.

Will get to that tomorrow.

**Comment by grogancolin** [comment]
Yep, can confirm this works now. 
Thanks!

**Comment by Jebbs** [comment]
I'm actually going to leave this open until I can get to the things @dmi7ry and I mentioned.

**Comment by dmi7ry** [comment]
On Windows also works fine now, thank you!

**Comment by Jebbs** [comment]
I'm going to close this as I'm not sure if there's anything that actually needs to be done still.
